'use strict';
const BUILD_QUESTIONS = [
  {title:'Campus research',topic:'Research',skill:'Subject → verb → purpose',words:['results','.','the','to','researchers','confirm','The','experiment','repeated','the'],answer:['The','researchers','repeated','the','experiment','to','confirm','the','results','.'],explanation:'The subject “The researchers” comes first, followed by the past-tense verb “repeated.” The infinitive phrase “to confirm…” gives the purpose.',clue:'Look for the subject and main verb before adding the purpose phrase.'},
  {title:'A useful routine',topic:'Study habits',skill:'Time phrase',words:['regularly','review','they','when','more','remember','can','Students','.'],answer:['Students','can','remember','more','when','they','review','regularly','.'],explanation:'“Students can remember more” is the main clause. The “when” clause explains the condition, and “regularly” modifies “review.”',clue:'A clause beginning with “when” needs its own subject and verb.'},
  {title:'Lab safety',topic:'Laboratory',skill:'Modal + passive voice',words:['temperature','stored','All','at','must','low','samples','a','be','.'],answer:['All','samples','must','be','stored','at','a','low','temperature','.'],explanation:'The modal “must” is followed by “be stored,” the passive form used when the samples receive the action.',clue:'After “must,” use the base verb; “be stored” keeps the sentence passive.'},
  {title:'A changing river',topic:'Earth science',skill:'Cause and result',words:['quickly','to','the','Heavy','rise','can','rain','cause','river','.'],answer:['Heavy','rain','can','cause','the','river','to','rise','quickly','.'],explanation:'“Heavy rain” is the subject, “can cause” is the verb phrase, and “the river to rise” is the result of that cause.',clue:'The pattern is subject + can cause + object + to-infinitive.'},
  {title:'Historical evidence',topic:'History',skill:'Relative clause',words:['old','.','archivist','The','century','found','document','over','that','a','was','the'],answer:['The','document','that','the','archivist','found','was','over','a','century','old','.'],explanation:'“That the archivist found” identifies the document. The main verb is “was,” followed by the age description.',clue:'Do not let the embedded “found” clause hide the main verb “was.”'},
  {title:'Urban planning',topic:'Cities',skill:'Contrast linker',words:['heavy','Although','carries','the','traffic','narrow','it','street','is','.'],answer:['Although','the','street','is','narrow','it','carries','heavy','traffic','.'],explanation:'“Although the street is narrow” is the contrast clause. The main clause follows with “it carries heavy traffic.”',clue:'An “although” clause comes before the contrasting main clause here.'},
  {title:'Animal navigation',topic:'Biology',skill:'Adverb placement',words:['migration','the','Some','navigate','birds','during','sun','use','to','.'],answer:['Some','birds','use','the','sun','to','navigate','during','migration','.'],explanation:'The sentence places the subject and verb first, then the object “the sun,” followed by purpose and time phrases.',clue:'“To navigate” explains purpose; “during migration” gives the time.'},
  {title:'Economic choices',topic:'Economics',skill:'Conditional sentence',words:['products','If','may','increase','less','consumers','prices','choose','expensive','.'],answer:['If','prices','increase','consumers','may','choose','less','expensive','products','.'],explanation:'The condition “If prices increase” comes first. The result clause begins with “consumers may choose…”.',clue:'After the if-clause, place the subject before the modal “may.”'},
  {title:'A clear comparison',topic:'Technology',skill:'Comparative phrase',words:['one','more','the','This','than','method','older','efficient','is','.'],answer:['This','method','is','more','efficient','than','the','older','one','.'],explanation:'The linking verb “is” connects the subject to the comparative phrase “more efficient than…”.',clue:'“More + adjective + than” is the comparison pattern.'},
  {title:'Careful conclusions',topic:'Data analysis',skill:'Concession linker',words:['consistent','the','however','sample','was','pattern','The','small','was','.'],answer:['The','sample','was','small','however','the','pattern','was','consistent','.'],explanation:'The first clause gives a limitation. “However” introduces the contrasting conclusion that the pattern was consistent.',clue:'“However” connects two contrasting ideas; punctuation separates the clauses.'}
];
const states=BUILD_QUESTIONS.map(()=>({placed:[],checked:false,revealed:false})); let current=0; const el=id=>document.getElementById(id);
function correct(i){return states[i].placed.join(' ')===BUILD_QUESTIONS[i].answer.join(' ')}
function updateNav(){el('build-nav').replaceChildren(...BUILD_QUESTIONS.map((q,i)=>{const b=document.createElement('button');b.type='button';b.className='nav-item';b.setAttribute('aria-current',String(i===current));b.setAttribute('aria-label',`Question ${i+1}: ${q.title}`);const n=document.createElement('span');n.className='nav-number';n.textContent=String(i+1).padStart(2,'0');const l=document.createElement('span');const name=document.createElement('span');name.className='nav-name';name.textContent=q.title;l.append(name);if(states[i].checked||states[i].revealed){const s=document.createElement('span');s.className='nav-state';s.textContent=states[i].checked?(correct(i)?'✓ Correct':'Review answer'):'Proof viewed';l.append(s)}b.append(n,l);b.onclick=()=>navigate(i);return b}));const done=states.filter(s=>s.checked).length;el('progress-text').textContent=`${done} of 10 checked`;el('progress-percent').textContent=`${done*10}%`;el('set-progress').value=done}
function render(){const q=BUILD_QUESTIONS[current],s=states[current];el('question-counter').textContent=`QUESTION ${String(current+1).padStart(2,'0')} / 10`;el('topic').textContent=q.topic;el('exercise-title').textContent=q.title;el('skill').textContent=q.skill;el('built-sentence').replaceChildren();el('built-sentence').classList.toggle('empty',!s.placed.length);s.placed.forEach((word,i)=>{const b=document.createElement('button');b.type='button';b.className='built-chip';b.textContent=word;b.title='Remove this word';b.onclick=()=>{s.placed.splice(i,1);s.checked=false;s.revealed=false;render()};el('built-sentence').append(b)});const occurrences={};el('word-bank').replaceChildren(...q.words.map((word)=>{const occurrence=occurrences[word]||0;occurrences[word]=occurrence+1;const b=document.createElement('button');b.type='button';b.className='word-chip';b.textContent=word;b.disabled=s.placed.filter(placed=>placed===word).length>occurrence;b.onclick=()=>{if(!b.disabled){s.placed.push(word);s.checked=false;s.revealed=false;render()}};return b}));el('selection-state').textContent=`${s.placed.length} word${s.placed.length===1?'':'s'} placed`;el('previous').disabled=current===0;el('next').disabled=current===9;el('feedback').hidden=true;el('proof').hidden=!(s.checked||s.revealed);el('reveal').textContent=s.checked||s.revealed?'Hide proof':'Show proof';el('reveal').setAttribute('aria-expanded',String(s.checked||s.revealed));if(s.checked)showFeedback();if(s.checked||s.revealed)renderProof();updateNav()}
function showFeedback(){el('feedback').replaceChildren(Object.assign(document.createElement('strong'),{textContent:correct(current)?'Correct.':'Not quite.'}),document.createTextNode(correct(current)?' The word order is complete.':' Compare your order with the proof below.'));el('feedback').hidden=false}
function renderProof(){const q=BUILD_QUESTIONS[current],s=states[current],r=el('proof-result');r.className='proof-result '+(s.checked?(correct(current)?'good':'wrong'):'revealed');el('proof-status').textContent=s.checked?(correct(current)?'Your sentence is correct.':`Your order has ${s.placed.length} of ${q.answer.length} words placed. The intended order is below.`):'Proof revealed before checking.';el('answer-tag').textContent='Completed sentence';el('completed-sentence').textContent=q.answer.join(' ').replace(/\s+([.,!?;:])/g,'$1');el('explanation').textContent=q.explanation;el('clue').textContent=q.clue}
function navigate(i){if(i<0||i>9)return;current=i;render();el('exercise-title').tabIndex=-1;el('exercise-title').focus({preventScroll:true});el('main').scrollIntoView({block:'start'})}
el('check').onclick=()=>{if(!states[current].placed.length){el('feedback').textContent='Place at least one word before checking.';el('feedback').hidden=false;return}states[current].checked=true;states[current].revealed=false;render()};el('clear').onclick=()=>{states[current]={placed:[],checked:false,revealed:false};render()};el('reveal').onclick=()=>{const s=states[current];if(!el('proof').hidden){el('proof').hidden=true;el('reveal').textContent='Show proof';el('reveal').setAttribute('aria-expanded','false');return}s.revealed=!s.checked;el('proof').hidden=false;el('reveal').textContent='Hide proof';el('reveal').setAttribute('aria-expanded','true');renderProof();updateNav()};el('previous').onclick=()=>navigate(current-1);el('next').onclick=()=>navigate(current+1);el('reset').onclick=()=>{states[current]={placed:[],checked:false,revealed:false};render()};render();
